# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
version: "3.8"
services:
  collector:
    image: otel/opentelemetry-collector:0.104.0
    command: ["--config=/etc/otelcol/config.yaml"]
    ports:
      - "4317:4317"
      - "4318:4318"
    volumes:
      - ./configs/collector.yaml:/etc/otelcol/config.yaml:ro
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - OTLP_GRPC_ENDPOINT=collector:4317
    ports:
      - "8080:8080"
    depends_on:
      - collector

