global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'otlp-go-dev'
    environment: 'development'

scrape_configs:
  # OpenTelemetry Collector metrics
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8888']
        labels:
          service: 'otel-collector'

  # OpenTelemetry Collector Prometheus exporter
  - job_name: 'otel-metrics'
    static_configs:
      - targets: ['otel-collector:8889']
        labels:
          service: 'application-metrics'

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Jaeger metrics
  - job_name: 'jaeger'
    static_configs:
      - targets: ['jaeger:14269']
        labels:
          service: 'jaeger'

# Alerting rules
rule_files:
  # - "alerts/*.yml"

# Alertmanager configuration
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets: ['alertmanager:9093']
